include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_final_locals
    - leading_newlines_in_multiline_strings
    - unnecessary_breaks
    # Ordering imports by vscode extentsion
    # - directives_ordering

analyzer:
  plugins:
    # Riverpod linter
    - custom_lint

  language:
    strict-raw-types: true
    strict-casts: true

  exclude:
  - lib/_skeleton/**/*
